package socialite.Absyn; // Java Package generated by the BNF Converter.

public abstract class AggregateSpecifier implements java.io.Serializable {
  public abstract <R,A> R accept(AggregateSpecifier.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(socialite.Absyn.AggregateWith p, A arg);
    public R visit(socialite.Absyn.NoAggregation p, A arg);

  }

}
