package socialite.Absyn; // Java Package generated by the BNF Converter.

public class AggregateWith extends AggregateSpecifier {
  public final Function function_;

  public AggregateWith(Function p1) { function_ = p1; }

  public <R,A> R accept(socialite.Absyn.AggregateSpecifier.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof socialite.Absyn.AggregateWith) {
      socialite.Absyn.AggregateWith x = (socialite.Absyn.AggregateWith)o;
      return this.function_.equals(x.function_);
    }
    return false;
  }

  public int hashCode() {
    return this.function_.hashCode();
  }


}
