package socialite.Absyn; // Java Package generated by the BNF Converter.

public abstract class ColumnDeclaration implements java.io.Serializable {
  public abstract <R,A> R accept(ColumnDeclaration.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(socialite.Absyn.ColumnDecl p, A arg);

  }

}
