package socialite.Absyn; // Java Package generated by the BNF Converter.

public class DeclarationConst extends Declaration {
  public final TypeName typename_;
  public final String uident_;
  public final Exp exp_;

  public DeclarationConst(TypeName p1, String p2, Exp p3) { typename_ = p1; uident_ = p2; exp_ = p3; }

  public <R,A> R accept(socialite.Absyn.Declaration.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof socialite.Absyn.DeclarationConst) {
      socialite.Absyn.DeclarationConst x = (socialite.Absyn.DeclarationConst)o;
      return this.typename_.equals(x.typename_) && this.uident_.equals(x.uident_) && this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.typename_.hashCode())+this.uident_.hashCode())+this.exp_.hashCode();
  }


}
