package socialite.Absyn; // Java Package generated by the BNF Converter.

public class MoreDim extends MoreDimensionsDeclaration {
  public final ListColumnDeclaration listcolumndeclaration_;

  public MoreDim(ListColumnDeclaration p1) { listcolumndeclaration_ = p1; }

  public <R,A> R accept(socialite.Absyn.MoreDimensionsDeclaration.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof socialite.Absyn.MoreDim) {
      socialite.Absyn.MoreDim x = (socialite.Absyn.MoreDim)o;
      return this.listcolumndeclaration_.equals(x.listcolumndeclaration_);
    }
    return false;
  }

  public int hashCode() {
    return this.listcolumndeclaration_.hashCode();
  }


}
