package socialite.Absyn; // Java Package generated by the BNF Converter.

public class PredicateSingle extends Predicate {
  public final String uident_;
  public final ListValue listvalue_;

  public PredicateSingle(String p1, ListValue p2) { uident_ = p1; listvalue_ = p2; }

  public <R,A> R accept(socialite.Absyn.Predicate.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof socialite.Absyn.PredicateSingle) {
      socialite.Absyn.PredicateSingle x = (socialite.Absyn.PredicateSingle)o;
      return this.uident_.equals(x.uident_) && this.listvalue_.equals(x.listvalue_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.uident_.hashCode())+this.listvalue_.hashCode();
  }


}
