package socialite.Absyn; // Java Package generated by the BNF Converter.

public class RuleBodyDef extends RuleBody {
  public final ListSubgoal listsubgoal_;

  public RuleBodyDef(ListSubgoal p1) { listsubgoal_ = p1; }

  public <R,A> R accept(socialite.Absyn.RuleBody.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof socialite.Absyn.RuleBodyDef) {
      socialite.Absyn.RuleBodyDef x = (socialite.Absyn.RuleBodyDef)o;
      return this.listsubgoal_.equals(x.listsubgoal_);
    }
    return false;
  }

  public int hashCode() {
    return this.listsubgoal_.hashCode();
  }


}
