package socialite.Absyn; // Java Package generated by the BNF Converter.

public abstract class RuleBody implements java.io.Serializable {
  public abstract <R,A> R accept(RuleBody.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(socialite.Absyn.RuleBodyDef p, A arg);

  }

}
