package socialite.Absyn; // Java Package generated by the BNF Converter.

public abstract class Rule implements java.io.Serializable {
  public abstract <R,A> R accept(Rule.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(socialite.Absyn.RuleDef p, A arg);

  }

}
