package socialite.Absyn; // Java Package generated by the BNF Converter.

public abstract class Subgoal implements java.io.Serializable {
  public abstract <R,A> R accept(Subgoal.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(socialite.Absyn.GoalPredicate p, A arg);
    public R visit(socialite.Absyn.GoalComparison p, A arg);
    public R visit(socialite.Absyn.GoalAssign p, A arg);

  }

}
