package socialite.Absyn; // Java Package generated by the BNF Converter.

public class ValueInt extends Value {
  public final Integer integer_;

  public ValueInt(Integer p1) { integer_ = p1; }

  public <R,A> R accept(socialite.Absyn.Value.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof socialite.Absyn.ValueInt) {
      socialite.Absyn.ValueInt x = (socialite.Absyn.ValueInt)o;
      return this.integer_.equals(x.integer_);
    }
    return false;
  }

  public int hashCode() {
    return this.integer_.hashCode();
  }


}
