package socialite.Absyn; // Java Package generated by the BNF Converter.

public class ValueVar extends Value {
  public final Variable variable_;

  public ValueVar(Variable p1) { variable_ = p1; }

  public <R,A> R accept(socialite.Absyn.Value.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof socialite.Absyn.ValueVar) {
      socialite.Absyn.ValueVar x = (socialite.Absyn.ValueVar)o;
      return this.variable_.equals(x.variable_);
    }
    return false;
  }

  public int hashCode() {
    return this.variable_.hashCode();
  }


}
