package socialite.Absyn; // Java Package generated by the BNF Converter.

public class Var extends Variable {
  public final String lident_;

  public Var(String p1) { lident_ = p1; }

  public <R,A> R accept(socialite.Absyn.Variable.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof socialite.Absyn.Var) {
      socialite.Absyn.Var x = (socialite.Absyn.Var)o;
      return this.lident_.equals(x.lident_);
    }
    return false;
  }

  public int hashCode() {
    return this.lident_.hashCode();
  }


}
