package socialite.Absyn; // Java Package generated by the BNF Converter.

public abstract class Variable implements java.io.Serializable {
  public abstract <R,A> R accept(Variable.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(socialite.Absyn.Var p, A arg);

  }

}
