package socialite.Absyn; // Java Package generated by the BNF Converter.

public class AtomSharded extends Atom {
  public final String uident_;
  public final Value value_;

  public AtomSharded(String p1, Value p2) { uident_ = p1; value_ = p2; }

  public <R,A> R accept(socialite.Absyn.Atom.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof socialite.Absyn.AtomSharded) {
      socialite.Absyn.AtomSharded x = (socialite.Absyn.AtomSharded)o;
      return this.uident_.equals(x.uident_) && this.value_.equals(x.value_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.uident_.hashCode())+this.value_.hashCode();
  }


}
