package socialite.Absyn; // Java Package generated by the BNF Converter.

public abstract class Atom implements java.io.Serializable {
  public abstract <R,A> R accept(Atom.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(socialite.Absyn.AtomSharded p, A arg);
    public R visit(socialite.Absyn.AtomSingle p, A arg);

  }

}
