package socialite.Absyn; // Java Package generated by the BNF Converter.

public class Comparison extends Equation {
  public final Exp exp_1, exp_2;
  public final CompOp compop_;

  public Comparison(Exp p1, CompOp p2, Exp p3) { exp_1 = p1; compop_ = p2; exp_2 = p3; }

  public <R,A> R accept(socialite.Absyn.Equation.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof socialite.Absyn.Comparison) {
      socialite.Absyn.Comparison x = (socialite.Absyn.Comparison)o;
      return this.exp_1.equals(x.exp_1) && this.compop_.equals(x.compop_) && this.exp_2.equals(x.exp_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.exp_1.hashCode())+this.compop_.hashCode())+this.exp_2.hashCode();
  }


}
