package socialite.Absyn; // Java Package generated by the BNF Converter.

public abstract class CompOp implements java.io.Serializable {
  public abstract <R,A> R accept(CompOp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(socialite.Absyn.CompOpEq p, A arg);
    public R visit(socialite.Absyn.CompOpGt p, A arg);
    public R visit(socialite.Absyn.CompOpLt p, A arg);
    public R visit(socialite.Absyn.CompOpGe p, A arg);
    public R visit(socialite.Absyn.CompOpLe p, A arg);

  }

}
