package socialite.Absyn; // Java Package generated by the BNF Converter.

public abstract class Constant implements java.io.Serializable {
  public abstract <R,A> R accept(Constant.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(socialite.Absyn.Const p, A arg);

  }

}
