package socialite.Absyn; // Java Package generated by the BNF Converter.

public class DeclarationDistributed extends Declaration {
  public final String uident_;
  public final TypeName typename_;
  public final Variable variable_;
  public final Range range_;
  public final MoreDimensionsDeclaration moredimensionsdeclaration_;

  public DeclarationDistributed(String p1, TypeName p2, Variable p3, Range p4, MoreDimensionsDeclaration p5) { uident_ = p1; typename_ = p2; variable_ = p3; range_ = p4; moredimensionsdeclaration_ = p5; }

  public <R,A> R accept(socialite.Absyn.Declaration.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof socialite.Absyn.DeclarationDistributed) {
      socialite.Absyn.DeclarationDistributed x = (socialite.Absyn.DeclarationDistributed)o;
      return this.uident_.equals(x.uident_) && this.typename_.equals(x.typename_) && this.variable_.equals(x.variable_) && this.range_.equals(x.range_) && this.moredimensionsdeclaration_.equals(x.moredimensionsdeclaration_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(37*(this.uident_.hashCode())+this.typename_.hashCode())+this.variable_.hashCode())+this.range_.hashCode())+this.moredimensionsdeclaration_.hashCode();
  }


}
