package socialite.Absyn; // Java Package generated by the BNF Converter.

public class DeclarationGlobal extends Declaration {
  public final String uident_;
  public final MoreDimensionsDeclaration moredimensionsdeclaration_;

  public DeclarationGlobal(String p1, MoreDimensionsDeclaration p2) { uident_ = p1; moredimensionsdeclaration_ = p2; }

  public <R,A> R accept(socialite.Absyn.Declaration.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof socialite.Absyn.DeclarationGlobal) {
      socialite.Absyn.DeclarationGlobal x = (socialite.Absyn.DeclarationGlobal)o;
      return this.uident_.equals(x.uident_) && this.moredimensionsdeclaration_.equals(x.moredimensionsdeclaration_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.uident_.hashCode())+this.moredimensionsdeclaration_.hashCode();
  }


}
