package socialite.Absyn; // Java Package generated by the BNF Converter.

public abstract class Declaration implements java.io.Serializable {
  public abstract <R,A> R accept(Declaration.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(socialite.Absyn.DeclarationDistributed p, A arg);
    public R visit(socialite.Absyn.DeclarationGlobal p, A arg);
    public R visit(socialite.Absyn.DeclarationConst p, A arg);

  }

}
