package socialite.Absyn; // Java Package generated by the BNF Converter.

public abstract class Equation implements java.io.Serializable {
  public abstract <R,A> R accept(Equation.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(socialite.Absyn.Comparison p, A arg);

  }

}
