package socialite.Absyn; // Java Package generated by the BNF Converter.

public class GoalEquation extends OneGoal {
  public final Equation equation_;

  public GoalEquation(Equation p1) { equation_ = p1; }

  public <R,A> R accept(socialite.Absyn.OneGoal.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof socialite.Absyn.GoalEquation) {
      socialite.Absyn.GoalEquation x = (socialite.Absyn.GoalEquation)o;
      return this.equation_.equals(x.equation_);
    }
    return false;
  }

  public int hashCode() {
    return this.equation_.hashCode();
  }


}
