package socialite.Absyn; // Java Package generated by the BNF Converter.

public class GoalPredicate extends OneGoal {
  public final Predicate predicate_;

  public GoalPredicate(Predicate p1) { predicate_ = p1; }

  public <R,A> R accept(socialite.Absyn.OneGoal.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof socialite.Absyn.GoalPredicate) {
      socialite.Absyn.GoalPredicate x = (socialite.Absyn.GoalPredicate)o;
      return this.predicate_.equals(x.predicate_);
    }
    return false;
  }

  public int hashCode() {
    return this.predicate_.hashCode();
  }


}
