package socialite.Absyn; // Java Package generated by the BNF Converter.

public class GoalAssign extends OneGoal {
  public final Variable variable_;
  public final Exp exp_;

  public GoalAssign(Variable p1, Exp p2) { variable_ = p1; exp_ = p2; }

  public <R,A> R accept(socialite.Absyn.OneGoal.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof socialite.Absyn.GoalAssign) {
      socialite.Absyn.GoalAssign x = (socialite.Absyn.GoalAssign)o;
      return this.variable_.equals(x.variable_) && this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.variable_.hashCode())+this.exp_.hashCode();
  }


}
