package socialite.Absyn; // Java Package generated by the BNF Converter.

public class PredicateStruct extends Predicate {
  public final Structure structure_;

  public PredicateStruct(Structure p1) { structure_ = p1; }

  public <R,A> R accept(socialite.Absyn.Predicate.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof socialite.Absyn.PredicateStruct) {
      socialite.Absyn.PredicateStruct x = (socialite.Absyn.PredicateStruct)o;
      return this.structure_.equals(x.structure_);
    }
    return false;
  }

  public int hashCode() {
    return this.structure_.hashCode();
  }


}
