package socialite.Absyn; // Java Package generated by the BNF Converter.

public abstract class Range implements java.io.Serializable {
  public abstract <R,A> R accept(Range.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(socialite.Absyn.RangeDef p, A arg);

  }

}
