package socialite.Absyn; // Java Package generated by the BNF Converter.

public abstract class RuleGoal implements java.io.Serializable {
  public abstract <R,A> R accept(RuleGoal.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(socialite.Absyn.RuleGoalDef p, A arg);

  }

}
