package socialite.Absyn; // Java Package generated by the BNF Converter.

public class RuleDef extends Rule {
  public final Predicate predicate_;
  public final ListRuleGoal listrulegoal_;

  public RuleDef(Predicate p1, ListRuleGoal p2) { predicate_ = p1; listrulegoal_ = p2; }

  public <R,A> R accept(socialite.Absyn.Rule.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof socialite.Absyn.RuleDef) {
      socialite.Absyn.RuleDef x = (socialite.Absyn.RuleDef)o;
      return this.predicate_.equals(x.predicate_) && this.listrulegoal_.equals(x.listrulegoal_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.predicate_.hashCode())+this.listrulegoal_.hashCode();
  }


}
