package socialite.Absyn; // Java Package generated by the BNF Converter.

public abstract class Term implements java.io.Serializable {
  public abstract <R,A> R accept(Term.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(socialite.Absyn.TermAtom p, A arg);
    public R visit(socialite.Absyn.TermValue p, A arg);
    public R visit(socialite.Absyn.TermCall p, A arg);

  }

}
