package socialite.Absyn; // Java Package generated by the BNF Converter.

public class TermCall extends Term {
  public final String dident_;
  public final ListTerm listterm_;

  public TermCall(String p1, ListTerm p2) { dident_ = p1; listterm_ = p2; }

  public <R,A> R accept(socialite.Absyn.Term.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof socialite.Absyn.TermCall) {
      socialite.Absyn.TermCall x = (socialite.Absyn.TermCall)o;
      return this.dident_.equals(x.dident_) && this.listterm_.equals(x.listterm_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.dident_.hashCode())+this.listterm_.hashCode();
  }


}
