package socialite.Absyn; // Java Package generated by the BNF Converter.

public class ValueConst extends Value {
  public final Constant constant_;

  public ValueConst(Constant p1) { constant_ = p1; }

  public <R,A> R accept(socialite.Absyn.Value.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof socialite.Absyn.ValueConst) {
      socialite.Absyn.ValueConst x = (socialite.Absyn.ValueConst)o;
      return this.constant_.equals(x.constant_);
    }
    return false;
  }

  public int hashCode() {
    return this.constant_.hashCode();
  }


}
