package socialite.Absyn; // Java Package generated by the BNF Converter.

public class ValueDouble extends Value {
  public final Double double_;

  public ValueDouble(Double p1) { double_ = p1; }

  public <R,A> R accept(socialite.Absyn.Value.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof socialite.Absyn.ValueDouble) {
      socialite.Absyn.ValueDouble x = (socialite.Absyn.ValueDouble)o;
      return this.double_.equals(x.double_);
    }
    return false;
  }

  public int hashCode() {
    return this.double_.hashCode();
  }


}
