
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Thu Sep 25 19:38:09 CEST 2014
//----------------------------------------------------

package socialite;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int _INTEGER_ = 22;
  public static final int UIdent = 24;
  public static final int _SYMB_19 = 21;
  public static final int _SYMB_18 = 20;
  public static final int _SYMB_17 = 19;
  public static final int _SYMB_16 = 18;
  public static final int _SYMB_15 = 17;
  public static final int _DOUBLE_ = 23;
  public static final int _SYMB_14 = 16;
  public static final int _SYMB_13 = 15;
  public static final int _SYMB_12 = 14;
  public static final int _SYMB_9 = 11;
  public static final int _SYMB_11 = 13;
  public static final int DIdent = 26;
  public static final int _SYMB_10 = 12;
  public static final int _SYMB_8 = 10;
  public static final int _SYMB_7 = 9;
  public static final int _SYMB_6 = 8;
  public static final int _SYMB_5 = 7;
  public static final int _SYMB_4 = 6;
  public static final int EOF = 0;
  public static final int _SYMB_3 = 5;
  public static final int _SYMB_2 = 4;
  public static final int _SYMB_1 = 3;
  public static final int _SYMB_0 = 2;
  public static final int error = 1;
  public static final int LIdent = 25;
}

